apiVersion: v1
kind: Secret
metadata:
  name: matomo
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "matomo.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.mariadb.auth.username }}
  mariadb_auth_username: {{ .Values.mariadb.auth.username | b64enc | quote }}
  {{ end }}
  {{ if .Values.mariadb.auth.password }}
  mariadb_auth_password: {{ .Values.mariadb.auth.password | b64enc | quote }}
  {{ end }}
  {{ if .Values.smtp.user }}
  smtp_user: {{ .Values.smtp.user | b64enc | quote }}
  {{ end }}
  {{ if .Values.smtp.password }}
  smtp_password: {{ .Values.smtp.password | b64enc | quote }}
  {{ end }}